import argparse
from fractions import Fraction
import json
import os
from pathlib import Path
import re
from unidecode import unidecode

import DataPipeline.general_functions as gf

## Below are constants used to handle regex parsing of measurements from recipe ingredient strings.
## Recognition of ingredient amounts could likely be improved with Natural Language Processor, but this is currently avoided in order to minimize imports.
METRIC_UNITS = ['gram', 'g', 'liter', 'litre', 'l']
METRIC_PREFIXES = ['kilo', 'k', 'hecto', 'h', 'deca', 'deka', 'da', 'deci', 'd', 'centi', 'c', 'mili', 'm']
US_UNITS = [
    'ounce', 'oz', 'pound', 'lb',
    'drop', 'dr', 'smidgen', 'smdg', 'pinch', 'pn', 'dash', 'ds', 
    'teaspoon',  'tsp', 't', 'tablespoon', 'tbsp', 'fluid ounce', 'fl oz',
    'cup', 'c', 'pint', 'pt', 'quart', 'qt', 'gallon', 'gal',
    ]

METRIC_UNITS_STRING = '|'.join(METRIC_UNITS).lower()
METRIC_PREFIXES_STRING = '|'.join(METRIC_PREFIXES).lower()
US_UNITS_STRING = '|'.join(US_UNITS).lower()

## These nasty looking patterns are built to extract units in the general format of <amount><unit_prefix><unit_suffix> .
## ex. "5 grams" (metric), "1.2 teaspoons" (US), "1 3/4 cup" (US), "2 apples" (Non-Standard).
## These should catch values with or without spaces, between brackets, etc. But this is regex so likely some uncaught failure points.
METRIC_PATTERN = rf'(?P<amount>(?:\d+(?:[.\s]\d+)?|\d+\/\d+|\.\d+))\s*?(?P<unit_prefix>{METRIC_PREFIXES_STRING})?\s?(?P<unit>({METRIC_UNITS_STRING})s?(?![a-zA-Z]))'
US_PATTERN = rf'(?P<amount>(?:\d+(?:[.\s]\d+)?|\d+\/\d+|\.\d+))\s*?(?P<unit>({US_UNITS_STRING})s?(?![a-zA-Z]))'
NON_STANDARD_PATTERN = rf'(?P<amount>(?:\d+(?:[.\s]\d+)?|\d+\/\d+|\.\d+))?\s*?(?P<object>[a-zA-Z\s-]+[a-zA-Z])'

## Nutrition pattern follows a similer but simpler <amount><unit_prefix><unit_suffix>.
NUTRITION_PATTERN = rf'(?P<amount>\d+)\s+?(?P<unit_prefix>{METRIC_PREFIXES_STRING})?\s?(?P<unit>[a-zA-Z]+)'

def parse_ingredient_str(ingredient_text: str) -> dict:
    '''
    Performs several rounds of regex and text parsing to extract Metric Units, US Units, and Non-Standard Units from a string describing a recipe ingredient.
    Where possible, will also provide a standardized unit conversion to either grams or militers.
    
    Args:
        ingredient_text: The raw string of an ingredient. Assumed to be taken from a recipe generated by serious_eats_data_pre_processing.py .

    Returns:
        return_dict: A dict containing the extracted recipe object (ex "carrot", "chicken"), the original amount and unit provided, and the gram or militer conversion of that amount.
    '''

    ## Initial text formatting.
    parsed_text = unidecode(ingredient_text).lower()
    parsed_text = re.sub(r'-', ' ', parsed_text)

    ## Metric is preferred, so extract its units with priority
    try:
        standard_unit_match = re.search(METRIC_PATTERN, parsed_text)
        
        standard_units = {
            'amount': standard_unit_match.group('amount'),
            'unit_prefix': standard_unit_match.group('unit_prefix'),
            'unit':  standard_unit_match.group('unit').rstrip('s')
            }
        
        ## Remove previously recognized matches from further analysis
        standard_sub_pattern = rf'{standard_unit_match.group('amount')}\s*?{standard_unit_match.group('unit_prefix')}?\s?{standard_unit_match.group('unit')}'
        parsed_text = re.sub(standard_sub_pattern, r'', parsed_text)

    ## If no matches found, set this dict to Nones
    except:
        standard_unit_match = None
        standard_units = {'amount': None, 'unit_prefix': None, 'unit': None}
    
    ## Extract US units of measurement next
    try:
        us_unit_match = re.search(US_PATTERN, parsed_text)
        us_units = {
            'amount': us_unit_match.group('amount'),
            'unit':  us_unit_match.group('unit').rstrip('s')
            }
        
        ## Remove previously recognized matches from further analysis
        us_sub_pattern = rf'{us_unit_match.group('amount')}\s*?{us_unit_match.group('unit')}'
        parsed_text = re.sub(us_sub_pattern, r'', parsed_text)

    ## If no matches found, set this dict to Nones
    except:
        us_unit_match = None
        us_units = {'amount': None, 'unit': None}

    ## Use remaining ingredient string to obtain non-standard measurments and the ingredient itself.
    parsed_text = re.sub(r'(?<=boneless|skinless),(?=\s*boneless|\s*skinless)', '', parsed_text) # Clunky and explicit fix for common logic-breaking pattern of describing cuts of meat.
    parsed_text = re.sub(r'\(.*?\)|\[.*?\]|\{.*?\}', '', parsed_text) # Remove brackets and any content between them.
    parsed_text = parsed_text.strip().lstrip(',').split(',')[0] # Get rid of leading commas and take text up to first non-leading comma.

    non_standard_match = re.search(NON_STANDARD_PATTERN, parsed_text)
    non_standard_objects = {
        'amount': non_standard_match.group('amount') if non_standard_match.group('amount') else None,
        'object':  non_standard_match.group('object').rstrip('s') # Regardless of previous matching, this is likely the ingredient name.
        }
    
    ## Use the Metric, US, and non-standard analysis to build the output dict.
    ingredient = non_standard_objects['object'].strip()
    ingredient = re.sub(r'\s\s+', ' ', ingredient) # Reduce multiple spaces to one.

    ## Combine unit information. Reminder that unit prefixes are only possible for metric.
    unit_prefix = standard_units['unit_prefix'] or None
    unit = standard_units['unit'] or us_units['unit'] or None
    unit_full = ((standard_units['unit_prefix'] or '') + (standard_units['unit'] or '')) or us_units['unit'] or None

    ## Parse out the format of the unit amount below.
    amount = standard_units['amount'] or us_units['amount'] or non_standard_objects['amount']
    if amount == None: # Assume that non-standard units are one instance. Examples here are "Fresh Cut Parsley", "Cojita Cheese for Topping", or "Pepper to Taste".
        amount = 1
    elif len(amount.strip().split()) == 2: # Convert a mixed fraction (ie "1 3/4") to a float (ie 1.75).
        amount = float(int(amount.strip().split()[0]) + Fraction(amount.strip().split()[1])) 
    else:
        if '/' in amount: # For a non-mixed fraction (ie "5/6").
            amount = float(Fraction(amount.strip()))
        else: # For a pure numeric string.
            amount = float(amount.strip())

    ## Get standardized conversion in grams or militers.
    std_amount, std_unit = gf.standardize_unit(amount, unit, unit_prefix)

    ## Build return dict.
    return_dict = {
        'ingredient': ingredient,
        'amount': amount,
        'unit': unit_full,
        'std_amount': std_amount,
        'std_unit': std_unit
    }

    return return_dict

def parse_nutrition_str(nutrition_text: str) -> dict:
    '''
    Reads a string of nutrition data and converts it to a dictionary of amount and unit.
    
    Args:
        nutrition_text: The raw string of a nutrition value. Assumed to be taken from a recipe generated by serious_eats_data_pre_processing.py .

    Returns:
        return_dict: A dict containing the extracted nutrition data split into amount and unit.
    '''

    ## Initial text formatting.
    parsed_text = unidecode(nutrition_text).lower()

    ## Search the string with match pattern constant.
    nutrition_match = re.match(NUTRITION_PATTERN, parsed_text)

    ## Format the amount to float and the unit to include prefix.
    amount = float(nutrition_match.group('amount').strip())
    unit_full = ((nutrition_match['unit_prefix'] or '') + (nutrition_match['unit'] or ''))

    ## Build return dict.
    return_dict = {
        'amount': amount,
        'unit': unit_full,
    }

    return return_dict

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Serious Eats Recipe Processing")
    parser.add_argument('--output-dir', '-o', type=str, default='./Data/SeriousEats/RecipesProcessed', help="Path to the output directory.")
    parser.add_argument('--pre-processed-dir', type=str, default='./Data/SeriousEats/SiteContentPreProcessed', help="Path to the directory containing the extracted extracted schema .json files of Serious Eats webpages. This should also include a summary dictionary.")
    
    ## Local file handling
    args = parser.parse_args()
    pre_processed_content_loc = Path(f'{args.pre_processed_dir}')
    recipe_processed_content_loc = Path(f'{args.output_dir}')
    recipe_processed_content_loc.mkdir(parents=True, exist_ok=True)

    ## Load the pre-processing summary dict crated by serious_eats_data-_pre_processing.py
    with open(f'{pre_processed_content_loc}/00_preprocessing_summary.json', 'r') as summ_file:
        summary_dict = json.load(summ_file)
    summ_file.close()

    ## Create an list of exceptions for future review.
    all_exceptions = []

    ## Iterate through every recipe file in the summary .json built by serious_eats_data_pre_processing.py
    for this_file in summary_dict['Recipe']['files']:
        this_file_json = this_file + '.json'
        this_file_json_path = f'{pre_processed_content_loc}/{this_file_json}'

        if os.path.isfile(this_file_json_path):
            with open (this_file_json_path, 'r') as this_json:
                this_recipe_dict = json.load(this_json)
            this_json.close()
            
            ## Attempt to read and parse ingredient data in the recipe. If there is an error, write it to the exception log.
            try:
               these_ingredients = (this_recipe_dict['recipeIngredient'])
               these_ingredients_processed = []
            except:
                all_exceptions.append({this_file : 'No recipeIngredient'})

            try:
                for this_ingredient in these_ingredients:
                    if (this_ingredient is not None) and (this_ingredient != '\xa0'): 
                        this_ingredient_processed = parse_ingredient_str(this_ingredient)
                        these_ingredients_processed.append(this_ingredient_processed)

            except Exception as E:
                all_exceptions.append({this_file : {this_ingredient: f'{E}'}})

            ## Attempt to read and parse nutrition data in the recipe. If there is an error, write it to the exception log.
            try:
               these_nutrition_labels = this_recipe_dict['nutrition']
               these_nutrition_labels_processed = {'@type': 'NutritionInformation'} # First entry to keep wtih schema.org formatting.
            except:
                all_exceptions.append({this_file : 'No nutrition'})

            try:
                for this_nutrition_label, this_nutrition_value in these_nutrition_labels.items():
                    if (this_nutrition_label is not None and this_nutrition_value is not None) and (this_nutrition_label != '\xa0' and this_nutrition_value != '\xa0'):
                        if (this_nutrition_label == 'servingSize'): # Manual exception for non-standard servingSize field.
                            these_nutrition_labels_processed[this_nutrition_label] = this_nutrition_value
                        elif (this_nutrition_label != '@type'):  # This is the schema.org label type
                            this_value_formatted = parse_nutrition_str(this_nutrition_value)
                            these_nutrition_labels_processed[this_nutrition_label] = this_value_formatted

            except Exception as E:
                all_exceptions.append({this_file : {f'{this_nutrition_label} - {this_nutrition_value}': f'{E}'}})

            ## Write the final output of the newly formatted recipe to file. Original data is kept were possible.
            try:
                this_recipe_dict_processed = this_recipe_dict
                this_recipe_dict_processed['recipeIngredient'] = these_ingredients_processed
                this_recipe_dict_processed['nutrition'] = these_nutrition_labels_processed

                gf.save_dict_to_file(this_recipe_dict_processed, f'{recipe_processed_content_loc}/{this_file}')

            except Exception as E:
                all_exceptions.append({this_file : f'Error saving: {E}'})     

    ## Write the exceptions summary to file
    gf.save_dict_to_file(all_exceptions, f'{recipe_processed_content_loc}/00_recipe_processing_exceptions')

    exit()
